# Generated by Django 6.0.3 on 2026-03-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_workspaceinvitelink'),
        ('workspaces', '0004_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_can_invite', models.BooleanField(default=True, help_text='Allow regular members (not just admins) to invite new people.', verbose_name='Members can invite')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_settings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace settings',
                'verbose_name_plural': 'Workspace settings',
            },
        ),
    ]
